Docs use diagram in app
ClearCalcs/custom-diagram-boilerplate pull request #25
Opened 2024-03-13 04:11 UTC by michaellisitsa

- [Add] Docs: How to use diagram in ClearCalcs

2024-03-13 21:35 UTC, JayserBeam requested changes
Everything else looks fine to me. Ping me and i'll re approve once the paragraph is completed.

2024-03-13 21:35 UTC, JayserBeam commented on docs/using-in-clearcalcs.md
> +ClearCalcs is a platform for structural engineers to use calculators to design safe structures such as buildings and civil infrastructure. The calculators are creatd
created*

2024-03-13 21:35 UTC, JayserBeam commented on docs/using-in-clearcalcs.md
> +ClearCalcs is a platform for structural engineers to use calculators to design safe structures such as buildings and civil infrastructure. The calculators are creatd
Looks like the train of thought left the station early

2024-03-13 23:59 UTC, michaellisitsa commented on docs/using-in-clearcalcs.md
> +ClearCalcs is a platform for structural engineers to use calculators to design safe structures such as buildings and civil infrastructure. The calculators are creatd
Nice pickup. updated in e9af6bd92c52edef032995672350641df0948630

2024-03-14 00:19 UTC, JayserBeam approved these changes
Added the remainder of the intro paragraph. I am able to follow along with the instructions. LGTM

2024-03-14 00:19 UTC, merged