Add SVGDOM limitations and instructions for adding assets and fonts
ClearCalcs/custom-diagram-boilerplate pull request #37
Opened 2024-06-19 06:06 UTC by michaellisitsa

- [Add] - Docs: Instructions on adding static assets
- [Add] - Docs: Experimental instructions on adding fonts
- [Add] - Docs: Limitations to SVGDOM API

2024-06-19 23:26 UTC, JayserBeam requested changes
Think it's picked the wrong route to take on a rebase, other than that, readable, understandable

2024-06-19 23:26 UTC, JayserBeam commented on docs/static-diagram-core.md
> +We add some boilerplate at top of `render.ts` called by the `render()`. The author should use the SVGDOM primitives for `document` and `window` in place of the browser equivalents and generate an SVG
This looks like it picked this over the existing changes but these were changed in another PR?

2024-06-19 23:37 UTC, michaellisitsa commented
@JayserBeam ready for re-review

2024-06-20 00:02 UTC, JayserBeam approved these changes
There's now a double blank line but its [ultra-nit-pick] so i'm not insanely concerned

2024-06-20 00:03 UTC, merged