Add Docs diagram release versioning
ClearCalcs/custom-diagram-boilerplate pull request #42
Opened 2024-06-26 04:40 UTC by michaellisitsa

- [Add] Docs: Semantic versioning of diagrams

2024-06-26 05:32 UTC, smith120bh requested changes
I love the versioning instructions and description. But for release, let's just make this a GitHub Action. Should be pretty straightforward, and make it considerably easier for both ourselves and any contractors. See my comments on Slack.
https://clearcalcs.slack.com/archives/C06E11WFJKA/p1719379658121879?thread_ts=1719373067.808309&cid=C06E11WFJKA

2024-06-26 09:44 UTC, michaellisitsa commented
@smith120bh as discussed separate ticket/PR will be made for automating CI workfow. Can you re-review?

2024-06-28 00:40 UTC, JulianGoh5 approved these changes
Quick start to version control looks good, happy to send this

Earlier discussion around automation has been captured in https://app.clickup.com/t/86cvtnyj4

2024-06-28 00:40 UTC, JulianGoh5 commented on docs/quick-start-version-control.md
> +rm -rf .parcel-cache/
> rm -rf

Use wisely 🤠

2024-06-28 00:40 UTC, merged